name: sponsors

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: ModyQyW
          SPONSORKIT_PATREON_TOKEN: ${{ secrets.SPONSORKIT_PATREON_TOKEN }}
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update sponsors"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
